# -*- mode: ruby -*-
# vi: set ft=ruby :
uniqId = Time.now.to_i

Vagrant.configure("2") do |config|

  
  # Define VM 1 - Ubuntu Webserver
  config.vm.define "ubuntu" do |ubuntu|
    #ubuntu.vm.box = "ubuntu/focal64"
    #ubuntu.vm.box_version = "20240821.0.1"
    ubuntu.vm.box = "blue-team-labs/fossa-gui" # Desktop install of focal fossa
    ubuntu.vm.box_version = "0.2.0"
    ubuntu.ssh.insert_key = false        # Do not replace the key
    ubuntu.ssh.username = "vagrant"      # SSH username
    ubuntu.ssh.password = "vagrant"      # SSH password
    ubuntu.ssh.private_key_path = nil    # Disable key-based auth
    ubuntu.vm.hostname = "ubuntu-sandbox"
    ubuntu.vm.network "private_network", ip: "192.168.56.11"
    ubuntu.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-#{uniqId}"
      vb.gui = true
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  # Define VM 2 - Kali External
  config.vm.define "kaliExternal" do |kaliExternal|
    kaliExternal.vm.box = "blue-team-labs/kali-2021.1"
    kaliExternal.vm.box_version = "0.2.0"
    kaliExternal.vm.hostname = "kali-external"
    kaliExternal.vm.network "private_network", ip: "192.168.56.12"
    kaliExternal.vm.provider "virtualbox" do |vb|
      vb.name = "kali-external-#{uniqId}"
      vb.gui = true
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  # Define VM 3 - Kali Internal
  config.vm.define "kaliInternal" do |kaliInternal|
    kaliInternal.vm.box = "blue-team-labs/kali-2021.1"
    kaliInternal.vm.box_version = "0.2.0"
    kaliInternal.vm.hostname = "kali-internal"
    kaliInternal.vm.network "private_network", ip: "192.168.56.13"
    kaliInternal.vm.provider "virtualbox" do |vb|
      vb.name = "kali-internal-#{uniqId}"
      vb.gui = true
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  # Define VM 4 - Microtik Router
  config.vm.define "microtik" do |microtik|
    microtik.vm.box = "blue-team-labs/routeros7-17-2"
    microtik.vm.box_version = "0.1.0"
    #microtik.vm.hostname = "microtik-router"
    microtik.vm.network "private_network", ip: "192.168.56.1"
    microtik.vm.provider "virtualbox" do |vb|
      vb.name = "Microtik-#{uniqId}"
      vb.gui = true
      vb.memory = 256
      vb.cpus = 1
    end
  end

end

